### ISSUE TITLE
Extend configuration file

### ISSUE THREAD

**Issue by benjavicente** [open-source-uc/canvas-stream#7]
Users should be able to customize how they want to download files, for example:

- Download files on demand
- Download directory
- Courses to omit

This could be done expanding the existing config file `config.toml`:

```toml
# Optional options are marked with

# API
url = 'https://to.canvas.com'
access_token = 'insert-random-chars-here'

# Download
output_path = '/absolute/path/to/directory'
in_parallel = false # of true
on_demand = true # or false
courses_to_ommit = [12345, 67890] 
```
